#!/bin/bash
while [[ "$#" -gt 0 ]]; do
    case $1 in
        --type) type="$2"; shift ;;
        --amount) amount="$2"; shift ;;
        --environment) environment="$2"; shift ;;
        *) echo "Unknown parameter passed: $1"; exit 1 ;;
    esac
    shift
done

pushd benchmarks
benchmarks=($(ls -1))
popd
for benchmark in "${benchmarks[@]}"; do
    echo "Generating benchmarks for $benchmark"
    if [ "$environment" == "github" ]; then
        pushd benchmarks
        prompt_content=$(cat $benchmark/prompt.txt)
        bug_content=$(cat $benchmark/bug.txt)
        popd
        python ./main.py --type $type --amount $amount --save-scripts True --results-directory "$benchmark"Artifacts --prompt-override "$prompt_content" --bug-override "$bug_content"
    else
        ./projectVenv/bin/python ./main.py --type $type --amount $amount --save-scripts True --model "mistral-small" --results-directory "$benchmark"Artifacts --prompt-override $benchmark/prompt.txt --bug-override $benchmark/bug.txt
    fi
done