name: 'Main Compile Action'
description: 'A composite action to run main compile tasks'
inputs:
  type:
    description: 'Type of the main.py execution'
    required: true
    default: 'openAI'
runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3 

    - name: Set up Python
      uses: actions/setup-python@v4 
      with:
        python-version: '3.9' 

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt 

    - name: Run main.py
      shell: bash
      run: python main.py --type "${{ inputs.type }}"