name: Benchmark Workflow

on:
  workflow_dispatch:
    inputs:
      model:
        description: "The model to use for the benchmark"
        required: true
        default: "mistral-small"

  check_run:
    types: [created, completed]

jobs:
  build:
    runs-on: [self-hosted, Linux, X64]
    
    defaults:
      run:
        working-directory: ${{ env.UNIQUE_DIR }}

    steps:
      - name: Create a unique directory within the workspace
        id: create-dir
        run: |
          TIMESTAMP=$(date +'%Y%m%d%H%M%S')
          UNIQUE_DIR="${GITHUB_WORKSPACE}_build_${TIMESTAMP}"
          mkdir -p "$UNIQUE_DIR"
          echo "UNIQUE_DIR=$UNIQUE_DIR" >> $GITHUB_ENV
          echo "Unique directory created: $UNIQUE_DIR"

      - name: Checkout repository to default directory
        uses: actions/checkout@v3

      - name: Move repository to the unique directory
        run: |
          mv $GITHUB_WORKSPACE/* $UNIQUE_DIR/
          echo "Moved repository to: $UNIQUE_DIR"

      - name: Set up Python
        uses: actions/setup-python@v4 
        with:
          python-version: '3.9' 

      - name: Run main_compile action
        uses: ./checks/benchmark
        with:
          type: "ollama"
          model: ${{ inputs.model }}
        env: 
          GPT_API_KEY: ${{ secrets.GPT_API_KEY }}
