name: Benchmark Workflow

on:
  workflow_dispatch:
    inputs:
      model:
        description: "The model to use for the benchmark"
        required: true
        default: "qwen2.5-coder:32b"

  check_run:
    types: [created, completed]

  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: [self-hosted, Linux, X64]

    outputs:
      UNIQUE_DIR: ${{ steps.create-dir.outputs.UNIQUE_DIR }}

    steps:
      - name: Create a unique directory within the workspace
        id: create-dir
        run: |
          TIMESTAMP=$(date +'%Y%m%d%H%M%S')
          UNIQUE_DIR="${GITHUB_WORKSPACE}_build_${{ inputs.model }}_${TIMESTAMP}"
          mkdir -p "$UNIQUE_DIR"
          echo "UNIQUE_DIR=$UNIQUE_DIR" >> $GITHUB_ENV
          echo "::set-output name=UNIQUE_DIR::$UNIQUE_DIR"
          echo "Unique directory created: $UNIQUE_DIR"

      - name: Checkout repository to default directory
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4 
        with:
          python-version: '3.9' 

      - name: Run main_compile action
        uses: ./checks/benchmark
        with:
          type: "ollama"
          model: ${{ inputs.model }}
        env: 
          GPT_API_KEY: ${{ secrets.GPT_API_KEY }}

  move_repository:
    needs: build
    runs-on: [self-hosted, Linux, X64]
    steps:
      - name: Move repository to the unique directory
        run: |
          echo "Moved repository to: ${{ needs.build.outputs.UNIQUE_DIR }}"
          mv $GITHUB_WORKSPACE/* ${{ needs.build.outputs.UNIQUE_DIR }}/